config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :new, :create, :show]
  root to: 'users#index'
end

app/models/user.rb
class User < ApplicationRecord
  has_one :user_address, dependent: :destroy
  accepts_nested_attributes_for :user_address
  has_one :company, dependent: :destroy
  accepts_nested_attributes_for :company
  validates :first_name, presence: true, length: { maximum: 100 }
  validates :last_name, presence: true, length: { maximum: 100 }
  validates :email_address, email: { disposable: true, message: "is invalid" }
  validates :date_of_birth, datetime: { before: :today, before_message: "is in the future", message: "is invalid" }
  validates :phone_number, phone: { allow_blank: true }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:update, :show]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_url, notice: 'User has been saved'
    else
      render 'new'
    end
  end

  private

  def set_user
      @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :email_address,
                                 :phone_number,
                                 :date_of_birth,
                                 :user_address_attributes => [
                                     :street,
                                     :city,
                                     :zip_code,
                                     :country],
                                 :company_attributes => [
                                     :name,
                                     :company_address_attributes => [
                                         :street,
                                         :city,
                                         :zip_code,
                                         :country]])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for setup_user(user) do |f| %>
  <%= f.input :first_name, label: 'First name', error: false, as: :string %>
  <br>
  <%= f.input :last_name, label: 'Last name', error: false, as: :string %>
  <br>
  <%= f.input :email_address, label: 'E-mail', error: false, as: :email %>
  <br>
  <%= f.input :date_of_birth, error: false, as: :date, start_year: Date.today.year - 90,
              end_year: Date.today.year %>
  <br>
  <%= f.input :phone_number, error: false, label: 'Phone number', as: :tel%>
  <br>
  <div><b>User address</b></div>
  <br>
  <%= f.simple_fields_for :user_address do |ff| %>
    <%= ff.input :country, label: 'Country', error: false, as: :string %>
    <br>
    <%= ff.input :city, label: 'City', error: false, as: :string %>
    <br>
    <%= ff.input :zip_code, label: 'Zip code', error: false, as: :string %>
    <br>
    <%= ff.input :street, label: 'Street', error: false, as: :string %>
    <br>
  <% end %>
  <div><b>User company</b></div>
  <br>
  <%= f.simple_fields_for :company do |ff| %>
    <%= ff.input :name, label: 'Company name', as: :string %>
    <br>
    <%= ff.simple_fields_for :company_address do |fff| %>
      <%= fff.input :country, label: 'Country', error: false, as: :string %>
      <br>
      <%= fff.input :city, label: 'City', error: false, as: :string %>
      <br>
      <%= fff.input :zip_code, label: 'Zip code', error: false, as: :string %>
      <br>
      <%= fff.input :street, label: 'Street', error: false, as: :string %>
      <br>
    <% end %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <ul>
          <% user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>
  <br>
  <%= f.button :submit, class: 'btn btn-primary'%>
<% end %>
<br>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td> <%= user.first_name %></td>
        <td> <%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<br>
<h1>User info</h1>
<style>
  table {
    border-collapse: collapse;
  }
  th, td {
    border: 1px solid #ccc;
    padding: 10px;
    text-align: left;
  }
</style>
<table>
  <tr>
    <th> First name </th>
    <th> Last name</th>
    <th> Email </th>
    <th> Date of birth </th>
    <th> Phone number </th>
  </tr>
  <tr>
    <td> <%= @user.first_name %></td>
    <td> <%= @user.last_name %>
    <td> <%= @user.email_address %></td>
    <td> <%= @user.date_of_birth %></td>
    <td> <%= @user.phone_number %></td>
  </tr>
</table>
<br>
<h1>User address </h1>
<table>
  <tr>
    <th> Country </th>
    <th> City </th>
    <th> Street </th>
    <th> Zip code </th>
  </tr>
  <tr>
    <td> <%= @user.user_address.country%></td>
    <td> <%= @user.user_address.city %>
    <td> <%= @user.user_address.street %></td>
    <td> <%= @user.user_address.zip_code %></td>
  </tr>
</table>
<br>
<% unless @user.company.company_address.nil? %>
  <h1>User company info </h1>
  <table>
    <tr>
      <th> Name </th>
      <th> Country </th>
      <th> City </th>
      <th> Street </th>
      <th> Zip code </th>
    </tr>
    <tr>
      <td> <%= @user.company.name %></td>
      <td> <%= @user.company.company_address.country%></td>
      <td> <%= @user.company.company_address.city %>
      <td> <%= @user.company.company_address.street %></td>
      <td> <%= @user.company.company_address.zip_code %></td>
    </tr>
  </table>
  <br>
<% end %>
<%= link_to 'Back', users_path %>